apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deployment
  labels:
    app: mongoexpress-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress-deployment
  template:
    metadata:
      labels:
        app: mongoexpress-deployment
    spec:
      containers:
        - name: mongoexpress-deployment
          image: mongo-express
          ports:
          - containerPort: 8081
          env: 
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom: 
              secretKeyRef:
                name: secret-mongodb 
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: 
              secretKeyRef:
                name: secret-mongodb 
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongoexpress-deployment
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081               
      nodePort: 30000