apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-deployment
  labels:
    app: mongodb-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongodb-deployment
  template:
    metadata: 
      labels:
        app: mongodb-deployment
    spec:
      containers:
      - name: mongodb-deployment
        image: mongo 
        ports: 
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: secret-mongodb 
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: secret-mongodb    
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017  